export const SERVER_HOST = "http://localhost:4000"

/** Access Levels */
export const ACCESS_GUEST_LEVEL = 0
export const ACCESS_NORMAL_USER_LEVEL = 1
export const ACCESS_ADMIN_LEVEL = 2


// PayPal
export const SANDBOX_CLIENT_ID = "Ac4j_8fLZjfVzp1TRfxKD6UXgcad-deN2F6nu438aO6wyQY8j1iSlxWzuX4QGDuPcC-yAwHBhvMCQ1D2"
export const PRODUCTION_CLIENT_ID = "TO_MAKE_A_LIVE_REAL_WORLD_APPLICATION_REPLACE_THIS_TEXT_WITH_YOUR_PRODUCTION_CLIENT_ID"

